name: ${project.name}
version: ${project.version}
main: ${project.group}.${project.name.toLowerCase()}.${project.name}
api-version: 1.19
author: Blugon
depend: [Kotlin]

permissions:
  explosionprotection.command:
    description: "Explosion Protection Command"
    default: op

commands:
  ep:
    description: "Explosion Protection Command"
    permission: explosionprotection.command