name: '${name}'
version: '${version}'
main: '${group}.${name.toLowerCase()}.${name}'
api-version: '${MinecraftVersion}'
author: Blugon
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:${KotlinVersion}
  - org.jetbrains.kotlin:kotlin-reflect:${KotlinVersion}

permissions:
  explosionprotection.command:
    description: "Explosion Protection Command"
    default: op

commands:
  ep:
    description: "Explosion Protection Command"
    permission: explosionprotection.command